---
  kind: "Pod"
  apiVersion: "v1"
  metadata: 
    name: "jenkins"
    labels: 
      name: "jenkins"
  spec: 
    containers: 
      - 
        name: "jenkins"
        image: "csanchez/jenkins-kubernetes"
        ports: 
          - 
            containerPort: 8080
            hostPort: 8080
          - 
            containerPort: 50000
            hostPort: 50000
        volumeMounts: 
          - 
            name: "jenkins-data"
            mountPath: "/var/jenkins_home"
    volumes: 
      - 
        name: "jenkins-data"
        # hostPath: 
        #   path: "/home/docker/jenkins"
        gcePersistentDisk:
          pdName: kubernetes-jenkins
          fsType: ext4
        # awsElasticBlockStore:
        #   volumeID: aws://<availability-zone>/<volume-id>
        #   fsType: ext4
