---
  kind: "Pod"
  apiVersion: "v1"
  metadata: 
    name: "jenkins"
    labels: 
      name: "jenkins"
  spec: 
    containers: 
      - 
        name: "jenkins"
        image: "csanchez/jenkins-kubernetes:latest"
        ports: 
          - 
            containerPort: 8080
          - 
            containerPort: 50000
        volumeMounts: 
          - 
            name: "jenkins-data"
            mountPath: "/var/jenkins_home"
        imagePullPolicy: Always
    volumes: 
      - 
        name: "jenkins-data"
        gcePersistentDisk:
          pdName: kubernetes-jenkins
          fsType: ext4
